# basics
model = "vgg7"
dataset = "cifar10"
task = "cls"

max_epochs = 5
batch_size = 512
learning_rate = 1e-2
accelerator = "cpu"
project = "vgg7-search-test"
seed = 42
log_every_n_steps = 5
load_name = "../mase_output/vgg_test_gpu_20_epochs/software/training_ckpts/best.ckpt"
load_type = "pl"

[search.search_space]
name = "graph/quantize/channel_size_modifier"

#[search.search_space.setup]
#by = 'name'

[search.search_space.seed.default.config]
# the only choice "NA" is used to indicate that layers are not quantized by default
name = ["NA"]

[search.search_space.seed.feature_layers_0.config]
name = ["output_only"]
channel_multiplier = [1, 2, 4]

[search.search_space.seed.feature_layers_1.config]
parent = ["feature_layers_0"]

[search.search_space.seed.feature_layers_3.config]
name = ["both"]
parent = ["feature_layers_0"]
channel_multiplier = [1, 2, 3, 4]

[search.search_space.seed.feature_layers_4.config]
parent = ["feature_layers_3"]

[search.search_space.seed.feature_layers_7.config]
name = ["both"]
parent = ["feature_layers_3"]
channel_multiplier = [1, 2, 3, 4]

[search.search_space.seed.feature_layers_8.config]
parent = ["feature_layers_7"]

[search.search_space.seed.feature_layers_10.config]
name = ["both"]
parent = ["feature_layers_7"]
channel_multiplier = [1, 2, 3, 4]

[search.search_space.seed.feature_layers_11.config]
name = ["input_only"]
parent = ["feature_layers_10"]

[search.search_space.seed.feature_layers_14.config]
name = ["input_only"]
parent = ["feature_layers_10"]

[search.strategy]
name = "optuna"
eval_mode = false

#[search.strategy.sw_runner.basic_train]
#data_loader = "train_dataloader"
#max_epochs = 10
#num_samples = 256
#optimizer = "adam"
#learning_rate = 1e-5
#weight_decay = 0
#lr_scheduler = "linear"
#num_warmup_steps = 0

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32

[search.strategy.setup]
n_jobs = 1
n_trials = 2
timeout = 20000
sampler = "tpe"
sum_scaled_metrics = true # single objective
direction = "maximize"

[search.strategy.metrics]
accuracy.scale = 1.0
accuracy.direction = "maximize"
